# .github/workflows/main_skillsphere-backend-vinay.yml

name: Build and deploy JAR app to Azure Web App - skillsphere-backend-vinay

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build Backend with Maven Wrapper
        working-directory: ./backend
        env: 
             APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
        run: |
          chmod +x mvnw
          ./mvnw clean package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_461BC9AF54944E15A43F3DAF6B083E19 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1FC39382063D4CB7A672AA1D45FCC596 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_771B0CF3996442AEAE1D9F48057DDF21 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'skillsphere-backend-vinay'
          slot-name: 'Production'
          package: '*.jar'
